### ISSUE TITLE
Enable tab completion

### ISSUE THREAD

**Issue by ocadaruma** [kawamuray/kmql#2]
Tab completion is helpful a lot to reduce typos and make writing queries fast.

jline3 has a built-in mechanism to enable completion based on given set of string (refs: https://www.javadoc.io/doc/org.jline/jline/latest/org.jline/org/jline/reader/impl/completer/StringsCompleter.html)

I imagine completion candidates like:
1. tables
    * Can be retrieved from TableRegistry
2. columns
    * Table doesn't holds columns, so we have to retrieve them by executing `show columns`
    * And tables aren't exists unless executing one query (or passing `--init-all`)
3. SQL reservation words (select, inner, having...)
    * Can be retrieved from hard-coded strings in source file or resource file

To address 2, I think we can separate table creation from preparation, and change like below:
- create all tables at start of kmql session
- retrieve all columns by executing `show columns` at start of kmql session (if not `--exec` mode), and create completion candidates
- `:expire` will `truncate` the table instead of `drop`

What do you think about this?

Thanks,

**Comment by kawamuray** [comment]
+1 for supporting completion 👍 

About the implementation strategy:

> To address 2, I think we can separate table creation from preparation, and change like below:

while I can almost agree with this strategy, one concern that I have in my mind is, if `kmql` somehow fails to detect the target tables which are being queried (currently it just does a dump regex matching), it could let the select statement to run against an existing but not initialized table that could result in showing empty result for users rather than the error telling the table doesn't exists, which is misleading I think. 

Given that it might be better to make each tables to return a kind of "create table description" which works for both creating tables and describing table's schema for completion, but it might not absolutely required.

**Comment by ocadaruma** [comment]
Hm, I can understand that.
> one concern that I have in my mind is, if kmql somehow fails to detect

Sounds nice, but I'm not sure how "create table description" should be.
> Given that it might be better to make each tables to return a kind of "create table description"

Such description should contain the list of columns, and since we don't want to repeat listing columns in multiple places, create-table sql should be auto-derived from column list I think.
Then, I think it should be like:
```
public class Column {
    String name;
    String type;
    boolean nullable;
}

public interface Table {
...
    List<Column> columns();
    List<Column> primaryKey();
...
    default String createTableSql() {
        ...
    }
}
```

Isn't too much? So just separating table-creation looks simpler?

**Comment by kawamuray** [comment]
> Isn't too much? So just separating table-creation looks simpler?

perhaps. yeah we may start with the simpler solution.
